### PR TITLE
Mirror option (solves #17), print settings via dropdown & PDF Icons for Keyboards page

### PR DESCRIPTION
**Pull request by 73567876543783**
Hi,

Today I started off with a PR for a simple button to mirror an image. After this I added PDF icons and lastly I turned the mirror button and all other print options into a dropdown menu. All these three changes are now combined in this one pull request. 

**Mirroring** (solves #17)
I wasn't able to fix all the mirrored labels yet. Some possible options:

- Make a second .ai file for the left sides. Unfortunately this would lead to a lot of redundancy for all the symmetric keyboards.
- Seperate the labels/scale from the images and combine them later via R. Unfortunately this would only be easy for the symmetric keyboards. The unsymmetric ones would still need two images.

I'll have to think about this some more, but for now a simple mirror as implemented in this commit could be enough. I'm happy to make further changes if you'd already thought of another way to solve this issue.

**PDF icons**
Inspired by the the todo list I added PDF icons to the Keyboards page.

The PDF icons link to a PDF file in the `images/pdf` folder. These PDF files, 1.4mb in total, were generated using the `makeAllPdfs.R` script. I used the A4 Rmarkdown template as a basis which could be changed to the letter template if preferred. 

`makeAllPdfs.R` also adds a pdf_path column to `keyboard.csv`, containing all links to the generated local PDF files. Subsequently pdf_path is used to generate a new links column containing, if available, a github link, a store link and a PDF link.

Because all PDF files are located in `images/pdf` and not the default `www` folder I had to update the server side of the shiny app using `addResourcePath()`.

**Print dropdown menu**
I wasn't satisfied with the mirror button and saw on the todo list that you already thought of a dropdown menu for printing options. The dropdown menu that was implemented allows for mirroring, selecting the print size and if the pdf should print separate pages for each keyboard.

On the UI side this cleans things up a little. On the server side I also tried to clean up the downloadHandler by removing it from the function it was wrapped in. The reactive inputs (size, seperate pages) replace the previous argument functions. 

One thing I couldn't fix yet was printing on seperate pages for the A4 format. In the letter Markdown template you use a for loop, this should also be implemented for the A4 template but I didn't have the time yet, should not be too difficult to fix.

### CODE REVIEW

**Comment by jhelvy** [comment]
Thanks! I very much appreciate the edits. I'll try and take a look at them in more detail later before I merge the PR.

**Comment by 73567876543783** [comment]
Cool, I'll gladly change some things up if you want to. I enjoyed working on it a lot and look forward to cross some more things off the to-do list.

**Comment by jhelvy** [comment]
Okay, I took a look and here are a few comments / suggestions:

- I'm fine with the mirroring just being a simple flip. It should be easy enough for users to understand the labels being reversed. the main purpose is to print it mirrored so people can test both hands to scale.
- On that note, I might add to the label for "Keyboard half" to say "Right (mirrored)" so that it's clear we're just mirroring the half (which isn't quite correct for some boards that actually have different halves and aren't symmetric).
- For the PDFs, I think we should make them for both A4 and Letter. Simplest solution to me is to modify the code to print to both and nest one more folder level deep, so `images/pdf/a4` and `images/pdf/letter`.
- If you do the above, then in the "keyboards" table I would make a new column called "PDF" and have `[a4]() / [letter]()` as the link text so the user can quickly download either.
- I didn't notice the for loop in the `printLetter.Rmd` file. Could you implement that in the `printA4.Rmd`? I believe that must have been added in a previous PR by someone else but maybe they forgot to update `printA4.Rmd`.
- I don't think we should re-render the PDFs on each push. They only need to be rebuilt when a new keyboard is added, which is a manual process anyway, so I could easily just run the `makeAllPdfs.R` script then. But I'm also not planning on adding more keyboards myself. It's just too time consuming. I'll try and clear out the existing requests in the current issues sometime over the holiday in a few weeks, but after that I'm not going to add more myself.

**Comment by 73567876543783** [comment]
Thanks for the comments, expect a commit in the next couple of days.

**Comment by 73567876543783** [comment]
Hi, I included most of your suggestions. 

- `makeAllPdfs.R` is now largely rewritten to make the code simpler and to make both A4 and Letter size PDFs.
- PDF links are now in a seperate column. I however chose to use the PDF icon with a hover over A4 or Letter title. With text links the height of the rows would double which didn't really improve the look of the table. An alternative is to remove the fixed width of the column to fit the text links better, but this would increase the width of all columns.
- Keyboard half now says Left (mirrored) and Right.
- I couldn't include the for loop correctly in `printA4.Rmd`. I also tried `knitr::include_graphics` but both the loop and knitr alternative somehow mess up. It seems that `papersize = a4` might cause these issues, as that's the main part that differs from `printLetter.Rmd`.

Additionally I tried to implement a Cherry/Choc filter in the compare tab and a Cherry/Choc checkmark in the keyboards tab. This filter solves #55 using the data from #56. First I wanted to do check boxes but this would fall out of line with the rest of the filter options. Because of that I just used radio buttons. Another todo for me would be to rework most radio buttons filters into checkboxes, this could also possibly simplify the function structure in `functions.R`.

**Comment by jhelvy** [comment]
Okay, I'm going to go ahead and merge this. The PDF icons in the table aren't my favorite solution for the A4 / Letter sizing, but it is compact and hopefully intuitive enough. Thanks for all these edits - slowly chipping away at the todo list!

**Pull request merged**
