### PR TITLE
feat: add ergoslab keyboard

### PR DESCRIPTION
**Pull request by tomsaleeba**
Hey @jhelvy, can you add the Ergoslab keyboard to this tool.

I designed this keyboard and I'm interested to see how it compares to other layouts.

I've updated the CSV and included a raw SVG, but I figure you still need to perform your magic to generate the image that the tool uses.

Thanks for making such a useful tool :rocket: :heart_eyes:

### CODE REVIEW

**Comment by jhelvy** [comment]
Sure, I'll add the image overlay. I have to manually adjust the Illustrator file to align each plate file, then export it as a png (I haven't figured out a better way to align everything...I think that fundamentally has to be done by a human).

**Comment by jhelvy** [comment]
It's up! Interesting layout - did you model this after the mitosis? The pinky stagger is pretty similar.

**Comment by tomsaleeba** [comment]
Thanks for the quick response.

> (I haven't figured out a better way to align everything...I think that fundamentally has to be done by a human)

Is it possible to store an x,y coordinate for each plate file and have some script that does the overlay? I'm totally guessing here, but I'm partial to things that are automated so it would be great if it were possible.

> It's up! Interesting layout - did you model this after the mitosis? The pinky stagger is pretty similar.

I did look at the mitosis while designing but I took the column stagger from the [Diverge 3](https://unikeyboard.io/product/diverge-3/). The thing I loved about the mitosis was how the one PCB handles all layers, by chopping sections out.

**Comment by jhelvy** [comment]
I thought about some sort of coordinate system, but the app is really simple - it just overlays multiple image files. The other issue is the labeling. With so many boards, I found it was difficult to tell the boards apart by relying on just color, so I add a label to each image. If I'm going to align everything by hand, it's easy enough to just add that label too while I'm in Illustrator. So dynamically adding a label would add even further complexity. I'm at the point where the time spent trying to automate all this probably isn't worth it since there really aren't that many boards coming up that often.

**Comment by tomsaleeba** [comment]
Wise words! Just because we *can* engineer a solution, doesn't mean we should.

**Pull request merged**
