### PR TITLE
add kimiko

### PR DESCRIPTION
**Pull request by BenRoe**
Hello,
Ben here from Keycapsss. I would like to add the Kimiko Split Keyboard to the splitKbCompare site.
Hope i added all necessary files.

### CODE REVIEW

**Comment by jhelvy** [comment]
Wow, thanks for getting the keymap all aligned! All I'll have to do is export the png and it'll be up!

**Comment by jhelvy** [comment]
Oh I just noticed you already did that too! Thanks, this makes it much easier to add.

**Comment by BenRoe** [comment]
Tried my best to make it easy as possible.
Thanks for the quick merge. The site is loading to death. Is this due to the building process?

**Comment by jhelvy** [comment]
No, I think it's something with the host site, shinyapps.io (it's free...can't complain too much). It gets sluggish from time to time. I just tried it again and it's more snappy now. 

I have a laundry list of speed up improvements that I'm planning on implementing this summer, so stay tuned!

**Pull request merged**
